### ISSUE TITLE
Integrate Sentry for error tracking

### ISSUE THREAD

**Issue by Craftplacer** [WinClassic/SimpleClassicTheme.Common#3]
- [x] Improved "crash" experience
- [x] Ask for consent before sending
- [x] Provide a way to see exception details before submitting
- [x] Implement global preference storing
- [x] Port to SCT.Common
